### ISSUE TITLE
remove those random paras and add something more meaningful

### ISSUE THREAD

**Issue by visheshhta** [ditdivdotdot/x-three-github#1]
those random paragraphs are really just taking up the valuable space available, **so just please remove all of them**.

**Comment by ditdivdotdot** [comment]
working on it

**Comment by ditdivdotdot** [comment]
but from which file should i remove those random paras? @visheshhta

**Comment by visheshhta** [comment]
oh sorry, didn't mention that, from abc.txt

**Comment by ditdivdotdot** [comment]
**please add @ditdivdotdot label from next time**, it'll help out when working in teams.

**Comment by visheshhta** [comment]
okay @ditdivdotdot

**Comment by ditdivdotdot** [comment]
cool

**Comment by visheshhta** [comment]
thanks @ditdivdotdot
